language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "iojs-v1"
  - "iojs-v2"

sudo: required

cache:
  directories:
    - node_modules

env:
  - DIALECT=oracle
  - ORACLE_FILE=oracle-xe-11.2.0-1.0.x86_64.rpm.zip
  - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
  - ORACLE_SID=XE

addons:
  postgresql: "9.4"

before_install:
  - .travis/oracle/download.sh
  - .travis/oracle/install.sh

before_script:
  - "mysql -e 'create database sequelize_test;'"
  - "psql -c 'create database sequelize_test;' -U postgres"
  - "psql sequelize_test -c 'create extension postgis;' -U postgres"

script:
  - "make test"

branches:
  only:
    - master
    - 1.7.0

matrix:
  fast_finish: true
  include:
    - node_js: "0.10"
      env: COVERAGE=true
  allow_failures:
    - node_js: "0.10"
      env: COVERAGE=true

notifications:
  hipchat:
    - 40e8850aaba9854ac4c9963bd33f8b@253477
  irc:
    - "chat.freenode.net#sequelizejs"
