language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "iojs-v1"
  - "iojs-v2"

sudo: required

cache:
  directories:
    - node_modules

env:
  global:
    - ORACLE_FILE=oracle-xe-11.2.0-1.0.x86_64.rpm.zip
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
    - ORACLE_SID=XE
  matrix:
    - DIALECT=oracle

addons:
  postgresql: "9.4"

before_install:
  - wget 'https://github.com/cbandy/travis-oracle/archive/v1.1.0.tar.gz'
  - mkdir -p .travis/oracle
  - tar --extract --gzip --strip-components 1 --directory .travis/oracle --file v1.1.0.tar.gz
  - .travis/oracle/download.sh
  - .travis/oracle/install.sh

before_script:
  - >
    { echo "CREATE USER williamgueiros IDENTIFIED BY tiger;";
      echo "GRANT CONNECT, RESOURCE to williamgueiros;";
    } | "$ORACLE_HOME/bin/sqlplus" -L -S / AS SYSDBA

script:
  - "make test"

branches:
  only:
    - master
    - 1.7.0

matrix:
  fast_finish: true
  include:
    - node_js: "0.10"
      env: COVERAGE=true
  allow_failures:
    - node_js: "0.10"
      env: COVERAGE=true

notifications:
  hipchat:
    - 40e8850aaba9854ac4c9963bd33f8b@253477
  irc:
    - "chat.freenode.net#sequelizejs"
